name: Go CI
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        platform: [ubuntu-lastest, macos-latest, windows-lastest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go ${{matrix.go-version}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Test
      run: |
        echo $(ls)
        export GO111MODULE="on"
        export GOPATH=""
        cd go
        echo $(ls)
        go test -v .
      shell: bash